name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up Docker Compose
      uses: docker/setup-qemu-action@v2

    - name: Ensure Docker Compose is available
      run: docker-compose version

    - name: Copy .env.example to .env
      run: cp ./1-integration-test/.env.example ./1-integration-test/.env

    - name: Make wait-for-it.sh executable
      run: chmod +x ./scripts/wait-for-it.sh

    - name: Wait for Database
      run: ./scripts/wait-for-it.sh db:5432 --timeout=30 --strict -- echo "Database is up"

    - name: Run integration script
      run: cd 1-integration-test && npm run test:integration
